### ISSUE TITLE
New Addon: ClayTech

### ISSUE THREAD

**Issue by ClayCoffee** [TheBusyBiscuit/Slimefun4-Wiki#34]
## Description
A new addon, ClayTech.

## Addon Resources (if applicable)
ClayTech: https://github.com/ClayCoffee/ClayTech
This addon added some new items & machines to Slimefun.

## Wiki page (If applicable)
There's no wiki currently.

## Slimefun Version
Slimefun-v4.2-NIGHTLY-1ab38ac

**Comment by TheBusyBiscuit** [comment]
Hi, thanks for making an Addon.
There are a few things I need to address though...

1. I can't seem to find a download link, we need a download link for the addons-page if you want your addon listed there.
2. Please provide a better description of what the addon does since that will ultimately decide whether someone installs it or not.
3. It looks like this addon is in chinese by default, since the majority of Slimefun users is english though, I think that a default language of english may better suited for a global audience.
4. On your README it says something about "contacting you for an authorization", could you elaborate what that means?

**Comment by ClayCoffee** [comment]
1.https://github.com/ClayCoffee/ClayTech/releases
The download link is here.
2.It added some weapons,armors,decorates things,machines(for ClayTech item crafting),and diffrent kinds of food & drink.It also improved Vanilla game experience, like High Speed Rails.
3.I'll change the default language to english later.
4.The authorization is only necessary for chinese users.Because chinese users might steal my plugin.(I've experience it before.)

**Comment by TheBusyBiscuit** [comment]
I will add your addon to the wiki at some point.

However it looks like your addon does not work with any official build...

**Comment by ClayCoffee** [comment]
![image](https://user-images.githubusercontent.com/29245388/76181176-390c1480-61fb-11ea-854e-38cd10a2441a.png)

**Comment by Glom1** [comment]
Coffee forver ！！

**Comment by TheBusyBiscuit** [comment]
Added it to the Addons page.
